Fixture/v0.2.5
enerBit/asic pull request #10
Opened 2024-01-24 01:02 UTC by JMTamayo

# Fixture v0.2.5 💜🏆

⚡ Implementation of ***trsd***, ***pep*** and ***PEM*** file definitions.
⚡ Implementation of ***.txa*** file extension.

🛠️ Fix broken link in `/src/asic/publication.py -> ASIC_MONTHLY_VERSION_PUBLICATION_SERVICE["url"]`.
🛠️ Fix ***mypy*** and ***flake8*** issues.
🛠️ Fix file overwriting of preprocessed files downloaded from FPT server.

2024-01-24 20:01 UTC, elpablete commented on src/asic/files/definitions/__init__.py
the module names should be in lowercase despite the asic file type name being in uppercase, change the .PME to .pme

2024-01-24 20:13 UTC, elpablete requested changes

2024-01-24 20:13 UTC, elpablete commented on .gitignore
I suggest using .env files instead of the platform specific env.ps1

2024-01-24 20:13 UTC, elpablete commented on src/asic/__init__.py
this looks like different behaviours of linters and automatic code fixes. Are you using ruff and black?

2024-01-24 20:13 UTC, elpablete commented on src/asic/cli.py
Again, linter behaviours, are you using ruff and black?

2024-01-24 20:13 UTC, elpablete commented on src/asic/cli.py
The file paths shenanigans with "\\", why are them needed? is it not posible to use the generic pathlib abstraction?

2024-01-25 01:56 UTC, JMTamayo commented on src/asic/__init__.py
No, I didn't use Ruff and Black. I used Black, flake8 and mypy.

2024-01-25 01:58 UTC, JMTamayo commented on src/asic/cli.py
I used Black, flake8 and mypy.

2024-01-25 02:12 UTC, JMTamayo commented on .gitignore
env.ps1 was included in previous versions. I cannot identify the reason for the change in that line, however, I understand the suggestion. I proceed to delete it from the .gitignore file.

2024-01-25 02:14 UTC, JMTamayo commented on src/asic/files/definitions/__init__.py
Okay, thanks! I'm gonna check!

2024-01-25 03:14 UTC, JMTamayo commented on src/asic/cli.py
I was thinking about this comment. The idea is to implement the normalized version in the name of the preprocessed file to download, after the period string "...\\YYYY-MM\\...", because when downloading 1 file with different versions, the .csv file is overwritten.

It is possible to use the pathlib.Path stored in ***local*** var as a reference to build the Path of the preprocessed file as follows:

<img width="547" alt="Screenshot 2024-01-24 at 22 11 47" src="https://github.com/enerBit/asic/assets/108230383/7f827016-01ed-4f71-9fca-38762491c158">

what do you think?

2024-01-25 03:23 UTC, JMTamayo reviewed
I wrote you some comments about your opinions. I made some changes which are available for your review and discussion.

2024-01-25 13:39 UTC, elpablete commented on src/asic/cli.py
ok, we will have to normalize this, but I'm going to approve the PR

2024-01-25 13:40 UTC, elpablete approved these changes

2024-01-25 13:40 UTC, merged